 CREATE TABLE category(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(150) NOT NULL);

 CREATE TABLE editor(
id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
second_name VARCHAR(100) NOT NULL,
login  VARCHAR(50) NOT NULL,
password  VARCHAR(100) NOT NULL);

CREATE TABLE article(
id BIGSERIAL PRIMARY KEY,
category_id BIGINT NOT NULL REFERENCES category(id),
title VARCHAR(200) NOT NULL,
body TEXT NOT NULL,
whenposted TIMESTAMP WITHOUT TIME ZONE);

CREATE TABLE user(
id BIGSERIAL PRIMARY KEY,
login VARCHAR(50) NOT NULL,
password VARCHAR(100) NOT NULL);

 CREATE TABLE comment(
id BIGSERIAL PRIMARY KEY,
article_id BIGINT NOT NULL REFERENCES article(id),
when_created TIMESTAMP NOT NULL,
content TEXT NOT NULL);

CREATE TABLE roles(
id BIGSERIAL PRIMARY KEY,
role_name VARCHAR(100) NOT NULL);